version: "3"

services:
    elastic:
        image: elasticsearch:5.3.0
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        volumes:
          - /home/lev/data:/usr/share/elasticsearch/data
          - /etc/localtime:/etc/localtime:ro
        networks:
          - elastic-test
        command: "elasticsearch --E cluster.name=logging-cluster --E node.data=true --E network.host=_site_ --E node.master=true --E node.max_local_storage_nodes=6"
        ports:
          - "9200:9200"
        ulimits:
          nofile:
            soft: 65536
            hard: 65536
    elastic-node-01:
        image: elasticsearch:5.3.0
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        volumes:
          - /home/lev/data:/usr/share/elasticsearch/data
          - /etc/localtime:/etc/localtime:ro
        networks:
          - elastic-test
        command: "elasticsearch --E cluster.name=logging-cluster --E node.data=true --E network.host=_site_ --E node.master=false --E discovery.zen.ping.unicast.hosts=elastic --E node.max_local_storage_nodes=6"
        links:
          - elastic
        ulimits:
          nofile:
            soft: 65536
            hard: 65536
    elastic-node-02:
        image: elasticsearch:5.3.0
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        volumes:
          - /home/lev/data:/usr/share/elasticsearch/data
          - /etc/localtime:/etc/localtime:ro
        networks:
          - elastic-test
        command: "elasticsearch --E cluster.name=logging-cluster --E node.data=true --E network.host=_site_ --E node.master=false --E discovery.zen.ping.unicast.hosts=elastic --E node.max_local_storage_nodes=6"
        links:
          - elastic
        ulimits:
          nofile:
            soft: 65536
            hard: 65536    
    kibana:
      image: kibana:5.3.0
      volumes:
        - /etc/localtime:/etc/localtime:ro
      command: kibana -e http://elastic:9200
      networks:
          - elastic-test
      links:
        - elastic
      ports:
        - "5601:5601"
    logstash:
      image: ozlevka/logstash-test
      volumes:
        - /home/lev/projects/elastic-logging/logstash:/app
        - /etc/localtime:/etc/localtime:ro
      networks:
          - elastic-test
      links:
        - elastic
      ports:
        - "5000:5000"
        
    cerebro:
      image: ozlevka/cerebro:0.6.5
      volumes:
        - /etc/localtime:/etc/localtime:ro
      networks:
          - elastic-test
      links:
        - elastic
      ports:
        - "9000:9000"

networks:
  elastic-test:
    driver: bridge