version: "2.1"

services:
    master:
        image: elasticsearch:5.2.2
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        volumes:
          - /home/lev/data:/usr/share/elasticsearch/data
          - /etc/localtime:/etc/localtime:ro
        network_mode: host
        command: "elasticsearch --E cluster.name=gce --E node.data=true --E node.master=true --E node.max_local_storage_nodes=6"
    kibana:
      image: kibana:5.2.2
      mem_limit: 512m
      volumes:
        - /etc/localtime:/etc/localtime:ro
      command: "kibana -e http://localhost:9200"
      network_mode: host
      depends_on:
        - master
    cerebro:
      image: ozlevka/cerebro:0.5.1
      mem_limit: 512m
      volumes:
        - /etc/localtime:/etc/localtime:ro
      network_mode: host