version: "3"

services:
  consul1: 
    image: progrium/consul
    hostname: consul1
    ports:
      - "8500:8500"
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        tag: consul1
    command: ["-server", "-bootstrap-expect=3", "-ui-dir", "/ui"]
  
  consul2:
    image: progrium/consul
    hostname: consul2
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        tag: consul2
    command: ["-server", "-join", "consul1"] 
  
  consul3:
    image: progrium/consul
    hostname: consul3
    logging:
      driver: syslog
      options: 
        syslog-address: tcp://localhost:5000
        tag: consul3
    command: ["-server", "-join", "consul1"]